remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [The title of your site]
description: Is there a coorelation between the amount of protein in a recipe and the Average Rating or Cooking Time?

gem "github-pages", group: :jekyll_plugins
